name: Generate GitHub User Stats

on:
  schedule:
    - cron: '0 19 1,10,20 * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v6

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/userstats.svg
        include-title: false
        hide-keys: joined, mostStarred, mostForked, followers, following
        max-languages: 9
        locale: en
      env:
        GITHUB_TOKEN: ${{secrets.GH_PAT}}